// src/app/layout.tsx
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import { LanguageProvider } from "@/context/LanguageContext"; // تأكد من استيراد Provider بشكل صحيح
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

// تحميل الخط من Google Fonts
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portal Web",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <LanguageProvider>  {/* لف المكونات بـ LanguageProvider */}
      <html lang="en"> {/* يمكن تغيير اللغة بناءً على السياق */}
        <body className={inter.className}>
          <Header />
          <ToastContainer theme="colored" position="top-center" />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </LanguageProvider>
  );
};

export default RootLayout;
